/*
 * generated by Xtext 2.28.0
 */
package org.xtext.example.dg.ide;


/**
 * Use this class to register ide components.
 */
public class DartGeneratorIdeModule extends AbstractDartGeneratorIdeModule {
}
