/*
 * generated by Xtext 2.28.0
 */
package org.xtext.example.dg.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.xtext.example.dg.DartGeneratorRuntimeModule;
import org.xtext.example.dg.DartGeneratorStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class DartGeneratorIdeSetup extends DartGeneratorStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new DartGeneratorRuntimeModule(), new DartGeneratorIdeModule()));
	}
	
}
