/*
 * generated by Xtext 2.28.0
 */
package org.xtext.example.dg.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class DartGeneratorAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("org/xtext/example/dg/parser/antlr/internal/InternalDartGenerator.tokens");
	}
}
