/*
 * generated by Xtext 2.28.0
 */
package org.xtext.example.dg.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.xtext.example.dg.parser.antlr.internal.InternalDartGeneratorParser;
import org.xtext.example.dg.services.DartGeneratorGrammarAccess;

public class DartGeneratorParser extends AbstractAntlrParser {

	@Inject
	private DartGeneratorGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalDartGeneratorParser createParser(XtextTokenStream stream) {
		return new InternalDartGeneratorParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "BDD";
	}

	public DartGeneratorGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(DartGeneratorGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
