/*
 * generated by Xtext 2.28.0
 */
package org.xtext.example.dg;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class DartGeneratorStandaloneSetup extends DartGeneratorStandaloneSetupGenerated {

	public static void doSetup() {
		new DartGeneratorStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
