/*
 * generated by Xtext 2.28.0
 */
package org.xtext.example.dg.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import org.xtext.example.DartGenerator.ui.internal.DartGeneratorActivator;

public class DartGeneratorUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return DartGeneratorActivator.getInstance().getInjector("org.xtext.example.dg.DartGenerator");
	}

}
