/*
 * generated by Xtext 2.28.0
 */
package org.xtext.example.mydsl.services;

import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.List;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Alternatives;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.EnumLiteralDeclaration;
import org.eclipse.xtext.EnumRule;
import org.eclipse.xtext.Grammar;
import org.eclipse.xtext.GrammarUtil;
import org.eclipse.xtext.Group;
import org.eclipse.xtext.Keyword;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.TerminalRule;
import org.eclipse.xtext.common.services.TerminalsGrammarAccess;
import org.eclipse.xtext.service.AbstractElementFinder;
import org.eclipse.xtext.service.GrammarProvider;

@Singleton
public class MyDslGrammarAccess extends AbstractElementFinder.AbstractGrammarElementFinder {
	
	public class BDDElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.BDD");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cBDDAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cBDDKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cTypeKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cTypeAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final RuleCall cTypeTypeBDDEnumRuleCall_3_1_0 = (RuleCall)cTypeAssignment_3_1.eContents().get(0);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cCollectionsKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_4_1 = (Keyword)cGroup_4.eContents().get(1);
		private final Assignment cCollectionsAssignment_4_2 = (Assignment)cGroup_4.eContents().get(2);
		private final RuleCall cCollectionsCollectionParserRuleCall_4_2_0 = (RuleCall)cCollectionsAssignment_4_2.eContents().get(0);
		private final Group cGroup_4_3 = (Group)cGroup_4.eContents().get(3);
		private final Keyword cCommaKeyword_4_3_0 = (Keyword)cGroup_4_3.eContents().get(0);
		private final Assignment cCollectionsAssignment_4_3_1 = (Assignment)cGroup_4_3.eContents().get(1);
		private final RuleCall cCollectionsCollectionParserRuleCall_4_3_1_0 = (RuleCall)cCollectionsAssignment_4_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_4_4 = (Keyword)cGroup_4.eContents().get(4);
		private final Keyword cRightCurlyBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		
		//BDD returns BDD:
		//    {BDD}
		//    'BDD'
		//    '{'
		//        ('type' type=TypeBDD)?
		//        ('collections' '{' collections+=Collection ( "," collections+=Collection)* '}' )?
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//{BDD}
		//'BDD'
		//'{'
		//    ('type' type=TypeBDD)?
		//    ('collections' '{' collections+=Collection ( "," collections+=Collection)* '}' )?
		//'}'
		public Group getGroup() { return cGroup; }
		
		//{BDD}
		public Action getBDDAction_0() { return cBDDAction_0; }
		
		//'BDD'
		public Keyword getBDDKeyword_1() { return cBDDKeyword_1; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//('type' type=TypeBDD)?
		public Group getGroup_3() { return cGroup_3; }
		
		//'type'
		public Keyword getTypeKeyword_3_0() { return cTypeKeyword_3_0; }
		
		//type=TypeBDD
		public Assignment getTypeAssignment_3_1() { return cTypeAssignment_3_1; }
		
		//TypeBDD
		public RuleCall getTypeTypeBDDEnumRuleCall_3_1_0() { return cTypeTypeBDDEnumRuleCall_3_1_0; }
		
		//('collections' '{' collections+=Collection ( "," collections+=Collection)* '}' )?
		public Group getGroup_4() { return cGroup_4; }
		
		//'collections'
		public Keyword getCollectionsKeyword_4_0() { return cCollectionsKeyword_4_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_4_1() { return cLeftCurlyBracketKeyword_4_1; }
		
		//collections+=Collection
		public Assignment getCollectionsAssignment_4_2() { return cCollectionsAssignment_4_2; }
		
		//Collection
		public RuleCall getCollectionsCollectionParserRuleCall_4_2_0() { return cCollectionsCollectionParserRuleCall_4_2_0; }
		
		//( "," collections+=Collection)*
		public Group getGroup_4_3() { return cGroup_4_3; }
		
		//","
		public Keyword getCommaKeyword_4_3_0() { return cCommaKeyword_4_3_0; }
		
		//collections+=Collection
		public Assignment getCollectionsAssignment_4_3_1() { return cCollectionsAssignment_4_3_1; }
		
		//Collection
		public RuleCall getCollectionsCollectionParserRuleCall_4_3_1_0() { return cCollectionsCollectionParserRuleCall_4_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_4_4() { return cRightCurlyBracketKeyword_4_4; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_5() { return cRightCurlyBracketKeyword_5; }
	}
	public class CollectionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.Collection");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cCollectionAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cCollectionKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cTitreKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cTitreAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final RuleCall cTitreEStringParserRuleCall_3_1_0 = (RuleCall)cTitreAssignment_3_1.eContents().get(0);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cDocumentsKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_4_1 = (Keyword)cGroup_4.eContents().get(1);
		private final Assignment cDocumentsAssignment_4_2 = (Assignment)cGroup_4.eContents().get(2);
		private final RuleCall cDocumentsDocumentsParserRuleCall_4_2_0 = (RuleCall)cDocumentsAssignment_4_2.eContents().get(0);
		private final Group cGroup_4_3 = (Group)cGroup_4.eContents().get(3);
		private final Keyword cCommaKeyword_4_3_0 = (Keyword)cGroup_4_3.eContents().get(0);
		private final Assignment cDocumentsAssignment_4_3_1 = (Assignment)cGroup_4_3.eContents().get(1);
		private final RuleCall cDocumentsDocumentsParserRuleCall_4_3_1_0 = (RuleCall)cDocumentsAssignment_4_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_4_4 = (Keyword)cGroup_4.eContents().get(4);
		private final Keyword cRightCurlyBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		
		//Collection returns Collection:
		//    {Collection}
		//    'Collection'
		//    '{'
		//        ('titre' titre=EString)?
		//        ('documents' '{' documents+=Documents ( "," documents+=Documents)* '}' )?
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//{Collection}
		//'Collection'
		//'{'
		//    ('titre' titre=EString)?
		//    ('documents' '{' documents+=Documents ( "," documents+=Documents)* '}' )?
		//'}'
		public Group getGroup() { return cGroup; }
		
		//{Collection}
		public Action getCollectionAction_0() { return cCollectionAction_0; }
		
		//'Collection'
		public Keyword getCollectionKeyword_1() { return cCollectionKeyword_1; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//('titre' titre=EString)?
		public Group getGroup_3() { return cGroup_3; }
		
		//'titre'
		public Keyword getTitreKeyword_3_0() { return cTitreKeyword_3_0; }
		
		//titre=EString
		public Assignment getTitreAssignment_3_1() { return cTitreAssignment_3_1; }
		
		//EString
		public RuleCall getTitreEStringParserRuleCall_3_1_0() { return cTitreEStringParserRuleCall_3_1_0; }
		
		//('documents' '{' documents+=Documents ( "," documents+=Documents)* '}' )?
		public Group getGroup_4() { return cGroup_4; }
		
		//'documents'
		public Keyword getDocumentsKeyword_4_0() { return cDocumentsKeyword_4_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_4_1() { return cLeftCurlyBracketKeyword_4_1; }
		
		//documents+=Documents
		public Assignment getDocumentsAssignment_4_2() { return cDocumentsAssignment_4_2; }
		
		//Documents
		public RuleCall getDocumentsDocumentsParserRuleCall_4_2_0() { return cDocumentsDocumentsParserRuleCall_4_2_0; }
		
		//( "," documents+=Documents)*
		public Group getGroup_4_3() { return cGroup_4_3; }
		
		//","
		public Keyword getCommaKeyword_4_3_0() { return cCommaKeyword_4_3_0; }
		
		//documents+=Documents
		public Assignment getDocumentsAssignment_4_3_1() { return cDocumentsAssignment_4_3_1; }
		
		//Documents
		public RuleCall getDocumentsDocumentsParserRuleCall_4_3_1_0() { return cDocumentsDocumentsParserRuleCall_4_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_4_4() { return cRightCurlyBracketKeyword_4_4; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_5() { return cRightCurlyBracketKeyword_5; }
	}
	public class EStringElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.EString");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cSTRINGTerminalRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cIDTerminalRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//EString returns ecore::EString:
		//    STRING | ID;
		@Override public ParserRule getRule() { return rule; }
		
		//STRING | ID
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//STRING
		public RuleCall getSTRINGTerminalRuleCall_0() { return cSTRINGTerminalRuleCall_0; }
		
		//ID
		public RuleCall getIDTerminalRuleCall_1() { return cIDTerminalRuleCall_1; }
	}
	public class DocumentsElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.Documents");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cDocumentsAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cDocumentsKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cIdKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cIdAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final RuleCall cIdEStringParserRuleCall_3_1_0 = (RuleCall)cIdAssignment_3_1.eContents().get(0);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cChampsKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_4_1 = (Keyword)cGroup_4.eContents().get(1);
		private final Assignment cChampsAssignment_4_2 = (Assignment)cGroup_4.eContents().get(2);
		private final RuleCall cChampsChampParserRuleCall_4_2_0 = (RuleCall)cChampsAssignment_4_2.eContents().get(0);
		private final Group cGroup_4_3 = (Group)cGroup_4.eContents().get(3);
		private final Keyword cCommaKeyword_4_3_0 = (Keyword)cGroup_4_3.eContents().get(0);
		private final Assignment cChampsAssignment_4_3_1 = (Assignment)cGroup_4_3.eContents().get(1);
		private final RuleCall cChampsChampParserRuleCall_4_3_1_0 = (RuleCall)cChampsAssignment_4_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_4_4 = (Keyword)cGroup_4.eContents().get(4);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cCollectionsKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_5_1 = (Keyword)cGroup_5.eContents().get(1);
		private final Assignment cCollectionsAssignment_5_2 = (Assignment)cGroup_5.eContents().get(2);
		private final RuleCall cCollectionsCollectionParserRuleCall_5_2_0 = (RuleCall)cCollectionsAssignment_5_2.eContents().get(0);
		private final Group cGroup_5_3 = (Group)cGroup_5.eContents().get(3);
		private final Keyword cCommaKeyword_5_3_0 = (Keyword)cGroup_5_3.eContents().get(0);
		private final Assignment cCollectionsAssignment_5_3_1 = (Assignment)cGroup_5_3.eContents().get(1);
		private final RuleCall cCollectionsCollectionParserRuleCall_5_3_1_0 = (RuleCall)cCollectionsAssignment_5_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_5_4 = (Keyword)cGroup_5.eContents().get(4);
		private final Keyword cRightCurlyBracketKeyword_6 = (Keyword)cGroup.eContents().get(6);
		
		//Documents returns Documents:
		//    {Documents}
		//    'Documents'
		//    '{'
		//        ('id' id=EString)?
		//        ('champs' '{' champs+=Champ ( "," champs+=Champ)* '}' )?
		//        ('collections' '{' collections+=Collection ( "," collections+=Collection)* '}' )?
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//{Documents}
		//'Documents'
		//'{'
		//    ('id' id=EString)?
		//    ('champs' '{' champs+=Champ ( "," champs+=Champ)* '}' )?
		//    ('collections' '{' collections+=Collection ( "," collections+=Collection)* '}' )?
		//'}'
		public Group getGroup() { return cGroup; }
		
		//{Documents}
		public Action getDocumentsAction_0() { return cDocumentsAction_0; }
		
		//'Documents'
		public Keyword getDocumentsKeyword_1() { return cDocumentsKeyword_1; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//('id' id=EString)?
		public Group getGroup_3() { return cGroup_3; }
		
		//'id'
		public Keyword getIdKeyword_3_0() { return cIdKeyword_3_0; }
		
		//id=EString
		public Assignment getIdAssignment_3_1() { return cIdAssignment_3_1; }
		
		//EString
		public RuleCall getIdEStringParserRuleCall_3_1_0() { return cIdEStringParserRuleCall_3_1_0; }
		
		//('champs' '{' champs+=Champ ( "," champs+=Champ)* '}' )?
		public Group getGroup_4() { return cGroup_4; }
		
		//'champs'
		public Keyword getChampsKeyword_4_0() { return cChampsKeyword_4_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_4_1() { return cLeftCurlyBracketKeyword_4_1; }
		
		//champs+=Champ
		public Assignment getChampsAssignment_4_2() { return cChampsAssignment_4_2; }
		
		//Champ
		public RuleCall getChampsChampParserRuleCall_4_2_0() { return cChampsChampParserRuleCall_4_2_0; }
		
		//( "," champs+=Champ)*
		public Group getGroup_4_3() { return cGroup_4_3; }
		
		//","
		public Keyword getCommaKeyword_4_3_0() { return cCommaKeyword_4_3_0; }
		
		//champs+=Champ
		public Assignment getChampsAssignment_4_3_1() { return cChampsAssignment_4_3_1; }
		
		//Champ
		public RuleCall getChampsChampParserRuleCall_4_3_1_0() { return cChampsChampParserRuleCall_4_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_4_4() { return cRightCurlyBracketKeyword_4_4; }
		
		//('collections' '{' collections+=Collection ( "," collections+=Collection)* '}' )?
		public Group getGroup_5() { return cGroup_5; }
		
		//'collections'
		public Keyword getCollectionsKeyword_5_0() { return cCollectionsKeyword_5_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_5_1() { return cLeftCurlyBracketKeyword_5_1; }
		
		//collections+=Collection
		public Assignment getCollectionsAssignment_5_2() { return cCollectionsAssignment_5_2; }
		
		//Collection
		public RuleCall getCollectionsCollectionParserRuleCall_5_2_0() { return cCollectionsCollectionParserRuleCall_5_2_0; }
		
		//( "," collections+=Collection)*
		public Group getGroup_5_3() { return cGroup_5_3; }
		
		//","
		public Keyword getCommaKeyword_5_3_0() { return cCommaKeyword_5_3_0; }
		
		//collections+=Collection
		public Assignment getCollectionsAssignment_5_3_1() { return cCollectionsAssignment_5_3_1; }
		
		//Collection
		public RuleCall getCollectionsCollectionParserRuleCall_5_3_1_0() { return cCollectionsCollectionParserRuleCall_5_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_5_4() { return cRightCurlyBracketKeyword_5_4; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_6() { return cRightCurlyBracketKeyword_6; }
	}
	public class ChampElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.Champ");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cChampAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cChampKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cChampKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cChampAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final RuleCall cChampTypeChampEnumRuleCall_3_1_0 = (RuleCall)cChampAssignment_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_4 = (Keyword)cGroup.eContents().get(4);
		
		//Champ returns Champ:
		//    {Champ}
		//    'Champ'
		//    '{'
		//        ('champ' champ=TypeChamp)?
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//{Champ}
		//'Champ'
		//'{'
		//    ('champ' champ=TypeChamp)?
		//'}'
		public Group getGroup() { return cGroup; }
		
		//{Champ}
		public Action getChampAction_0() { return cChampAction_0; }
		
		//'Champ'
		public Keyword getChampKeyword_1() { return cChampKeyword_1; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//('champ' champ=TypeChamp)?
		public Group getGroup_3() { return cGroup_3; }
		
		//'champ'
		public Keyword getChampKeyword_3_0() { return cChampKeyword_3_0; }
		
		//champ=TypeChamp
		public Assignment getChampAssignment_3_1() { return cChampAssignment_3_1; }
		
		//TypeChamp
		public RuleCall getChampTypeChampEnumRuleCall_3_1_0() { return cChampTypeChampEnumRuleCall_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_4() { return cRightCurlyBracketKeyword_4; }
	}
	
	public class TypeBDDElements extends AbstractElementFinder.AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.TypeBDD");
		private final EnumLiteralDeclaration cFIREBASEEnumLiteralDeclaration = (EnumLiteralDeclaration)rule.eContents().get(1);
		private final Keyword cFIREBASEFIREBASEKeyword_0 = (Keyword)cFIREBASEEnumLiteralDeclaration.eContents().get(0);
		
		//enum TypeBDD returns TypeBDD:
		//                FIREBASE = 'FIREBASE';
		public EnumRule getRule() { return rule; }
		
		//FIREBASE = 'FIREBASE'
		public EnumLiteralDeclaration getFIREBASEEnumLiteralDeclaration() { return cFIREBASEEnumLiteralDeclaration; }
		
		//'FIREBASE'
		public Keyword getFIREBASEFIREBASEKeyword_0() { return cFIREBASEFIREBASEKeyword_0; }
	}
	public class TypeChampElements extends AbstractElementFinder.AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.TypeChamp");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cSTRINGEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cSTRINGSTRINGKeyword_0_0 = (Keyword)cSTRINGEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cBOOLEANEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cBOOLEANBOOLEANKeyword_1_0 = (Keyword)cBOOLEANEnumLiteralDeclaration_1.eContents().get(0);
		private final EnumLiteralDeclaration cMAPEnumLiteralDeclaration_2 = (EnumLiteralDeclaration)cAlternatives.eContents().get(2);
		private final Keyword cMAPMAPKeyword_2_0 = (Keyword)cMAPEnumLiteralDeclaration_2.eContents().get(0);
		private final EnumLiteralDeclaration cARRAYEnumLiteralDeclaration_3 = (EnumLiteralDeclaration)cAlternatives.eContents().get(3);
		private final Keyword cARRAYARRAYKeyword_3_0 = (Keyword)cARRAYEnumLiteralDeclaration_3.eContents().get(0);
		private final EnumLiteralDeclaration cNULLEnumLiteralDeclaration_4 = (EnumLiteralDeclaration)cAlternatives.eContents().get(4);
		private final Keyword cNULLNULLKeyword_4_0 = (Keyword)cNULLEnumLiteralDeclaration_4.eContents().get(0);
		private final EnumLiteralDeclaration cTIMESTAMPEnumLiteralDeclaration_5 = (EnumLiteralDeclaration)cAlternatives.eContents().get(5);
		private final Keyword cTIMESTAMPTIMESTAMPKeyword_5_0 = (Keyword)cTIMESTAMPEnumLiteralDeclaration_5.eContents().get(0);
		private final EnumLiteralDeclaration cGEOPOINTEnumLiteralDeclaration_6 = (EnumLiteralDeclaration)cAlternatives.eContents().get(6);
		private final Keyword cGEOPOINTGEOPOINTKeyword_6_0 = (Keyword)cGEOPOINTEnumLiteralDeclaration_6.eContents().get(0);
		private final EnumLiteralDeclaration cREFERENCEEnumLiteralDeclaration_7 = (EnumLiteralDeclaration)cAlternatives.eContents().get(7);
		private final Keyword cREFERENCEREFERENCEKeyword_7_0 = (Keyword)cREFERENCEEnumLiteralDeclaration_7.eContents().get(0);
		private final EnumLiteralDeclaration cNUMBEREnumLiteralDeclaration_8 = (EnumLiteralDeclaration)cAlternatives.eContents().get(8);
		private final Keyword cNUMBERNUMBERKeyword_8_0 = (Keyword)cNUMBEREnumLiteralDeclaration_8.eContents().get(0);
		
		//enum TypeChamp returns TypeChamp:
		//                STRING = 'STRING' | BOOLEAN = 'BOOLEAN' | MAP = 'MAP' | ARRAY = 'ARRAY' | NULL = 'NULL' | TIMESTAMP = 'TIMESTAMP' | GEOPOINT = 'GEOPOINT' | REFERENCE = 'REFERENCE' | NUMBER = 'NUMBER';
		public EnumRule getRule() { return rule; }
		
		//STRING = 'STRING' | BOOLEAN = 'BOOLEAN' | MAP = 'MAP' | ARRAY = 'ARRAY' | NULL = 'NULL' | TIMESTAMP = 'TIMESTAMP' | GEOPOINT = 'GEOPOINT' | REFERENCE = 'REFERENCE' | NUMBER = 'NUMBER'
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//STRING = 'STRING'
		public EnumLiteralDeclaration getSTRINGEnumLiteralDeclaration_0() { return cSTRINGEnumLiteralDeclaration_0; }
		
		//'STRING'
		public Keyword getSTRINGSTRINGKeyword_0_0() { return cSTRINGSTRINGKeyword_0_0; }
		
		//BOOLEAN = 'BOOLEAN'
		public EnumLiteralDeclaration getBOOLEANEnumLiteralDeclaration_1() { return cBOOLEANEnumLiteralDeclaration_1; }
		
		//'BOOLEAN'
		public Keyword getBOOLEANBOOLEANKeyword_1_0() { return cBOOLEANBOOLEANKeyword_1_0; }
		
		//MAP = 'MAP'
		public EnumLiteralDeclaration getMAPEnumLiteralDeclaration_2() { return cMAPEnumLiteralDeclaration_2; }
		
		//'MAP'
		public Keyword getMAPMAPKeyword_2_0() { return cMAPMAPKeyword_2_0; }
		
		//ARRAY = 'ARRAY'
		public EnumLiteralDeclaration getARRAYEnumLiteralDeclaration_3() { return cARRAYEnumLiteralDeclaration_3; }
		
		//'ARRAY'
		public Keyword getARRAYARRAYKeyword_3_0() { return cARRAYARRAYKeyword_3_0; }
		
		//NULL = 'NULL'
		public EnumLiteralDeclaration getNULLEnumLiteralDeclaration_4() { return cNULLEnumLiteralDeclaration_4; }
		
		//'NULL'
		public Keyword getNULLNULLKeyword_4_0() { return cNULLNULLKeyword_4_0; }
		
		//TIMESTAMP = 'TIMESTAMP'
		public EnumLiteralDeclaration getTIMESTAMPEnumLiteralDeclaration_5() { return cTIMESTAMPEnumLiteralDeclaration_5; }
		
		//'TIMESTAMP'
		public Keyword getTIMESTAMPTIMESTAMPKeyword_5_0() { return cTIMESTAMPTIMESTAMPKeyword_5_0; }
		
		//GEOPOINT = 'GEOPOINT'
		public EnumLiteralDeclaration getGEOPOINTEnumLiteralDeclaration_6() { return cGEOPOINTEnumLiteralDeclaration_6; }
		
		//'GEOPOINT'
		public Keyword getGEOPOINTGEOPOINTKeyword_6_0() { return cGEOPOINTGEOPOINTKeyword_6_0; }
		
		//REFERENCE = 'REFERENCE'
		public EnumLiteralDeclaration getREFERENCEEnumLiteralDeclaration_7() { return cREFERENCEEnumLiteralDeclaration_7; }
		
		//'REFERENCE'
		public Keyword getREFERENCEREFERENCEKeyword_7_0() { return cREFERENCEREFERENCEKeyword_7_0; }
		
		//NUMBER = 'NUMBER'
		public EnumLiteralDeclaration getNUMBEREnumLiteralDeclaration_8() { return cNUMBEREnumLiteralDeclaration_8; }
		
		//'NUMBER'
		public Keyword getNUMBERNUMBERKeyword_8_0() { return cNUMBERNUMBERKeyword_8_0; }
	}
	
	private final BDDElements pBDD;
	private final TypeBDDElements eTypeBDD;
	private final CollectionElements pCollection;
	private final EStringElements pEString;
	private final DocumentsElements pDocuments;
	private final ChampElements pChamp;
	private final TypeChampElements eTypeChamp;
	
	private final Grammar grammar;
	
	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public MyDslGrammarAccess(GrammarProvider grammarProvider,
			TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pBDD = new BDDElements();
		this.eTypeBDD = new TypeBDDElements();
		this.pCollection = new CollectionElements();
		this.pEString = new EStringElements();
		this.pDocuments = new DocumentsElements();
		this.pChamp = new ChampElements();
		this.eTypeChamp = new TypeChampElements();
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("org.xtext.example.mydsl.MyDsl".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	@Override
	public Grammar getGrammar() {
		return grammar;
	}
	
	
	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//BDD returns BDD:
	//    {BDD}
	//    'BDD'
	//    '{'
	//        ('type' type=TypeBDD)?
	//        ('collections' '{' collections+=Collection ( "," collections+=Collection)* '}' )?
	//    '}';
	public BDDElements getBDDAccess() {
		return pBDD;
	}
	
	public ParserRule getBDDRule() {
		return getBDDAccess().getRule();
	}
	
	//enum TypeBDD returns TypeBDD:
	//                FIREBASE = 'FIREBASE';
	public TypeBDDElements getTypeBDDAccess() {
		return eTypeBDD;
	}
	
	public EnumRule getTypeBDDRule() {
		return getTypeBDDAccess().getRule();
	}
	
	//Collection returns Collection:
	//    {Collection}
	//    'Collection'
	//    '{'
	//        ('titre' titre=EString)?
	//        ('documents' '{' documents+=Documents ( "," documents+=Documents)* '}' )?
	//    '}';
	public CollectionElements getCollectionAccess() {
		return pCollection;
	}
	
	public ParserRule getCollectionRule() {
		return getCollectionAccess().getRule();
	}
	
	//EString returns ecore::EString:
	//    STRING | ID;
	public EStringElements getEStringAccess() {
		return pEString;
	}
	
	public ParserRule getEStringRule() {
		return getEStringAccess().getRule();
	}
	
	//Documents returns Documents:
	//    {Documents}
	//    'Documents'
	//    '{'
	//        ('id' id=EString)?
	//        ('champs' '{' champs+=Champ ( "," champs+=Champ)* '}' )?
	//        ('collections' '{' collections+=Collection ( "," collections+=Collection)* '}' )?
	//    '}';
	public DocumentsElements getDocumentsAccess() {
		return pDocuments;
	}
	
	public ParserRule getDocumentsRule() {
		return getDocumentsAccess().getRule();
	}
	
	//Champ returns Champ:
	//    {Champ}
	//    'Champ'
	//    '{'
	//        ('champ' champ=TypeChamp)?
	//    '}';
	public ChampElements getChampAccess() {
		return pChamp;
	}
	
	public ParserRule getChampRule() {
		return getChampAccess().getRule();
	}
	
	//enum TypeChamp returns TypeChamp:
	//                STRING = 'STRING' | BOOLEAN = 'BOOLEAN' | MAP = 'MAP' | ARRAY = 'ARRAY' | NULL = 'NULL' | TIMESTAMP = 'TIMESTAMP' | GEOPOINT = 'GEOPOINT' | REFERENCE = 'REFERENCE' | NUMBER = 'NUMBER';
	public TypeChampElements getTypeChampAccess() {
		return eTypeChamp;
	}
	
	public EnumRule getTypeChampRule() {
		return getTypeChampAccess().getRule();
	}
	
	//terminal ID: '^'?('a'..'z'|'A'..'Z'|'_') ('a'..'z'|'A'..'Z'|'_'|'0'..'9')*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	}
	
	//terminal INT returns ecore::EInt: ('0'..'9')+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	}
	
	//terminal STRING:
	//            '"' ( '\\' . /* 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' */ | !('\\'|'"') )* '"' |
	//            "'" ( '\\' . /* 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' */ | !('\\'|"'") )* "'"
	//        ;
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	}
	
	//terminal ML_COMMENT : '/*' -> '*/';
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	}
	
	//terminal SL_COMMENT : '//' !('\n'|'\r')* ('\r'? '\n')?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	}
	
	//terminal WS         : (' '|'\t'|'\r'|'\n')+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	}
	
	//terminal ANY_OTHER: .;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	}
}
