/*
 * generated by Xtext 2.28.0
 */
package org.xtext.example.dg.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractDartGeneratorScopeProvider extends DelegatingScopeProvider {
}
