/*
 * generated by Xtext 2.28.0
 */
package org.xtext.example.dg.ui;

import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;
import org.xtext.example.DartGenerator.ui.internal.DartGeneratorActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class DartGeneratorExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(DartGeneratorActivator.class);
	}
	
	@Override
	protected Injector getInjector() {
		DartGeneratorActivator activator = DartGeneratorActivator.getInstance();
		return activator != null ? activator.getInjector(DartGeneratorActivator.ORG_XTEXT_EXAMPLE_DG_DARTGENERATOR) : null;
	}

}
