/*
 * generated by Xtext 2.28.0
 */
package org.xtext.example.dg.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class DartGeneratorUiModule extends AbstractDartGeneratorUiModule {

	public DartGeneratorUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
